/*
 * This file is generated by jOOQ.
 */
package com.ninjarmm.dao.jooq.tables.records;


import com.ninjarmm.dao.jooq.tables.Device;
import com.ninjarmm.dao.jooq.tables.interfaces.IDevice;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.UUID;

import javax.annotation.processing.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "device", schema = "public", uniqueConstraints = {
    @UniqueConstraint(name = "device_pk", columnNames = {"id"})
})
public class DeviceRecord extends UpdatableRecordImpl<DeviceRecord> implements Record7<UUID, String, String, String, UUID, OffsetDateTime, BigDecimal>, IDevice {

    private static final long serialVersionUID = 627323975;

    /**
     * Setter for <code>public.device.id</code>.
     */
    @Override
    public DeviceRecord setId(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>public.device.id</code>.
     */
    @Id
    @Column(name = "id", nullable = false)
    @Override
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.device.systemName</code>.
     */
    @Override
    public DeviceRecord setSystemname(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>public.device.systemName</code>.
     */
    @Column(name = "systemName")
    @Override
    public String getSystemname() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.device.deviceType</code>.
     */
    @Override
    public DeviceRecord setDevicetype(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>public.device.deviceType</code>.
     */
    @Column(name = "deviceType")
    @Override
    public String getDevicetype() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.device.lastModifiedBy</code>.
     */
    @Override
    public DeviceRecord setLastmodifiedby(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>public.device.lastModifiedBy</code>.
     */
    @Column(name = "lastModifiedBy")
    @Override
    public String getLastmodifiedby() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.device.customerid</code>.
     */
    @Override
    public DeviceRecord setCustomerid(UUID value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>public.device.customerid</code>.
     */
    @Column(name = "customerid")
    @Override
    public UUID getCustomerid() {
        return (UUID) get(4);
    }

    /**
     * Setter for <code>public.device.lastmodifieddatetime</code>.
     */
    @Override
    public DeviceRecord setLastmodifieddatetime(OffsetDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>public.device.lastmodifieddatetime</code>.
     */
    @Column(name = "lastmodifieddatetime")
    @Override
    public OffsetDateTime getLastmodifieddatetime() {
        return (OffsetDateTime) get(5);
    }

    /**
     * Setter for <code>public.device.devicecost</code>.
     */
    @Override
    public DeviceRecord setDevicecost(BigDecimal value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>public.device.devicecost</code>.
     */
    @Column(name = "devicecost")
    @Override
    public BigDecimal getDevicecost() {
        return (BigDecimal) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<UUID, String, String, String, UUID, OffsetDateTime, BigDecimal> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<UUID, String, String, String, UUID, OffsetDateTime, BigDecimal> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<UUID> field1() {
        return Device.DEVICE.ID;
    }

    @Override
    public Field<String> field2() {
        return Device.DEVICE.SYSTEMNAME;
    }

    @Override
    public Field<String> field3() {
        return Device.DEVICE.DEVICETYPE;
    }

    @Override
    public Field<String> field4() {
        return Device.DEVICE.LASTMODIFIEDBY;
    }

    @Override
    public Field<UUID> field5() {
        return Device.DEVICE.CUSTOMERID;
    }

    @Override
    public Field<OffsetDateTime> field6() {
        return Device.DEVICE.LASTMODIFIEDDATETIME;
    }

    @Override
    public Field<BigDecimal> field7() {
        return Device.DEVICE.DEVICECOST;
    }

    @Override
    public UUID component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getSystemname();
    }

    @Override
    public String component3() {
        return getDevicetype();
    }

    @Override
    public String component4() {
        return getLastmodifiedby();
    }

    @Override
    public UUID component5() {
        return getCustomerid();
    }

    @Override
    public OffsetDateTime component6() {
        return getLastmodifieddatetime();
    }

    @Override
    public BigDecimal component7() {
        return getDevicecost();
    }

    @Override
    public UUID value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getSystemname();
    }

    @Override
    public String value3() {
        return getDevicetype();
    }

    @Override
    public String value4() {
        return getLastmodifiedby();
    }

    @Override
    public UUID value5() {
        return getCustomerid();
    }

    @Override
    public OffsetDateTime value6() {
        return getLastmodifieddatetime();
    }

    @Override
    public BigDecimal value7() {
        return getDevicecost();
    }

    @Override
    public DeviceRecord value1(UUID value) {
        setId(value);
        return this;
    }

    @Override
    public DeviceRecord value2(String value) {
        setSystemname(value);
        return this;
    }

    @Override
    public DeviceRecord value3(String value) {
        setDevicetype(value);
        return this;
    }

    @Override
    public DeviceRecord value4(String value) {
        setLastmodifiedby(value);
        return this;
    }

    @Override
    public DeviceRecord value5(UUID value) {
        setCustomerid(value);
        return this;
    }

    @Override
    public DeviceRecord value6(OffsetDateTime value) {
        setLastmodifieddatetime(value);
        return this;
    }

    @Override
    public DeviceRecord value7(BigDecimal value) {
        setDevicecost(value);
        return this;
    }

    @Override
    public DeviceRecord values(UUID value1, String value2, String value3, String value4, UUID value5, OffsetDateTime value6, BigDecimal value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    @Override
    public void from(IDevice from) {
        setId(from.getId());
        setSystemname(from.getSystemname());
        setDevicetype(from.getDevicetype());
        setLastmodifiedby(from.getLastmodifiedby());
        setCustomerid(from.getCustomerid());
        setLastmodifieddatetime(from.getLastmodifieddatetime());
        setDevicecost(from.getDevicecost());
    }

    @Override
    public <E extends IDevice> E into(E into) {
        into.from(this);
        return into;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DeviceRecord
     */
    public DeviceRecord() {
        super(Device.DEVICE);
    }

    /**
     * Create a detached, initialised DeviceRecord
     */
    public DeviceRecord(UUID id, String systemname, String devicetype, String lastmodifiedby, UUID customerid, OffsetDateTime lastmodifieddatetime, BigDecimal devicecost) {
        super(Device.DEVICE);

        set(0, id);
        set(1, systemname);
        set(2, devicetype);
        set(3, lastmodifiedby);
        set(4, customerid);
        set(5, lastmodifieddatetime);
        set(6, devicecost);
    }
}
