/*
 * This file is generated by jOOQ.
 */
package com.ninjarmm.dao.jooq.tables.interfaces;


import java.io.Serializable;
import java.time.OffsetDateTime;
import java.util.UUID;

import javax.annotation.processing.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "customer_service", schema = "public", uniqueConstraints = {
    @UniqueConstraint(name = "customer_service_pk", columnNames = {"id"})
})
public interface ICustomerService extends Serializable {

    /**
     * Setter for <code>public.customer_service.id</code>.
     */
    public ICustomerService setId(UUID value);

    /**
     * Getter for <code>public.customer_service.id</code>.
     */
    @Id
    @Column(name = "id", nullable = false)
    public UUID getId();

    /**
     * Setter for <code>public.customer_service.customerid</code>.
     */
    public ICustomerService setCustomerid(UUID value);

    /**
     * Getter for <code>public.customer_service.customerid</code>.
     */
    @Column(name = "customerid")
    public UUID getCustomerid();

    /**
     * Setter for <code>public.customer_service.serviceid</code>.
     */
    public ICustomerService setServiceid(UUID value);

    /**
     * Getter for <code>public.customer_service.serviceid</code>.
     */
    @Column(name = "serviceid")
    public UUID getServiceid();

    /**
     * Setter for <code>public.customer_service.lastmodifiedby</code>.
     */
    public ICustomerService setLastmodifiedby(String value);

    /**
     * Getter for <code>public.customer_service.lastmodifiedby</code>.
     */
    @Column(name = "lastmodifiedby")
    public String getLastmodifiedby();

    /**
     * Setter for <code>public.customer_service.lastmodifieddatetime</code>.
     */
    public ICustomerService setLastmodifieddatetime(OffsetDateTime value);

    /**
     * Getter for <code>public.customer_service.lastmodifieddatetime</code>.
     */
    @Column(name = "lastmodifieddatetime")
    public OffsetDateTime getLastmodifieddatetime();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ICustomerService
     */
    public void from(ICustomerService from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ICustomerService
     */
    public <E extends ICustomerService> E into(E into);
}
