/*
 * This file is generated by jOOQ.
 */
package com.ninjarmm.dao.jooq.tables.interfaces;


import java.io.Serializable;
import java.time.OffsetDateTime;
import java.util.UUID;

import javax.annotation.processing.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "customer", schema = "public", uniqueConstraints = {
    @UniqueConstraint(name = "customers_pk", columnNames = {"id"})
})
public interface ICustomer extends Serializable {

    /**
     * Setter for <code>public.customer.id</code>.
     */
    public ICustomer setId(UUID value);

    /**
     * Getter for <code>public.customer.id</code>.
     */
    @Id
    @Column(name = "id", nullable = false)
    public UUID getId();

    /**
     * Setter for <code>public.customer.name</code>.
     */
    public ICustomer setName(String value);

    /**
     * Getter for <code>public.customer.name</code>.
     */
    @Column(name = "name")
    public String getName();

    /**
     * Setter for <code>public.customer.lastModifiedBy</code>.
     */
    public ICustomer setLastmodifiedby(String value);

    /**
     * Getter for <code>public.customer.lastModifiedBy</code>.
     */
    @Column(name = "lastModifiedBy")
    public String getLastmodifiedby();

    /**
     * Setter for <code>public.customer.lastmodifieddatetime</code>.
     */
    public ICustomer setLastmodifieddatetime(OffsetDateTime value);

    /**
     * Getter for <code>public.customer.lastmodifieddatetime</code>.
     */
    @Column(name = "lastmodifieddatetime")
    public OffsetDateTime getLastmodifieddatetime();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ICustomer
     */
    public void from(ICustomer from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ICustomer
     */
    public <E extends ICustomer> E into(E into);
}
