/*
 * This file is generated by jOOQ.
 */
package com.ninjarmm.dao.jooq.tables.interfaces;


import java.io.Serializable;
import java.time.OffsetDateTime;
import java.util.UUID;

import javax.annotation.processing.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Entity
@Table(name = "user", schema = "public", uniqueConstraints = {
    @UniqueConstraint(name = "user_pkey", columnNames = {"id"})
})
public interface IUser extends Serializable {

    /**
     * Setter for <code>public.user.id</code>.
     */
    public IUser setId(UUID value);

    /**
     * Getter for <code>public.user.id</code>.
     */
    @Id
    @Column(name = "id", nullable = false)
    public UUID getId();

    /**
     * Setter for <code>public.user.username</code>.
     */
    public IUser setUsername(String value);

    /**
     * Getter for <code>public.user.username</code>.
     */
    @Column(name = "username", nullable = false)
    public String getUsername();

    /**
     * Setter for <code>public.user.password</code>.
     */
    public IUser setPassword(String value);

    /**
     * Getter for <code>public.user.password</code>.
     */
    @Column(name = "password", nullable = false)
    public String getPassword();

    /**
     * Setter for <code>public.user.lastModifiedBy</code>.
     */
    public IUser setLastmodifiedby(String value);

    /**
     * Getter for <code>public.user.lastModifiedBy</code>.
     */
    @Column(name = "lastModifiedBy")
    public String getLastmodifiedby();

    /**
     * Setter for <code>public.user.lastmodifieddatetime</code>.
     */
    public IUser setLastmodifieddatetime(OffsetDateTime value);

    /**
     * Getter for <code>public.user.lastmodifieddatetime</code>.
     */
    @Column(name = "lastmodifieddatetime")
    public OffsetDateTime getLastmodifieddatetime();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface IUser
     */
    public void from(IUser from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface IUser
     */
    public <E extends IUser> E into(E into);
}
