/*
 * This file is generated by jOOQ.
 */
package com.ninjarmm.dao.jooq;


import com.ninjarmm.dao.jooq.tables.Customer;
import com.ninjarmm.dao.jooq.tables.CustomerService;
import com.ninjarmm.dao.jooq.tables.Device;
import com.ninjarmm.dao.jooq.tables.Service;
import com.ninjarmm.dao.jooq.tables.User;

import java.util.Arrays;
import java.util.List;

import javax.annotation.processing.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -173512779;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.customer</code>.
     */
    public final Customer CUSTOMER = Customer.CUSTOMER;

    /**
     * The table <code>public.customer_service</code>.
     */
    public final CustomerService CUSTOMER_SERVICE = CustomerService.CUSTOMER_SERVICE;

    /**
     * The table <code>public.device</code>.
     */
    public final Device DEVICE = Device.DEVICE;

    /**
     * The table <code>public.service</code>.
     */
    public final Service SERVICE = Service.SERVICE;

    /**
     * The table <code>public.user</code>.
     */
    public final User USER = User.USER;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            Customer.CUSTOMER,
            CustomerService.CUSTOMER_SERVICE,
            Device.DEVICE,
            Service.SERVICE,
            User.USER);
    }
}
