/*
 * This file is generated by jOOQ.
 */
package com.ninjarmm.dao.jooq;


import com.ninjarmm.dao.jooq.tables.Customer;
import com.ninjarmm.dao.jooq.tables.CustomerService;
import com.ninjarmm.dao.jooq.tables.Device;
import com.ninjarmm.dao.jooq.tables.Service;
import com.ninjarmm.dao.jooq.tables.User;

import javax.annotation.processing.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.customer</code>.
     */
    public static final Customer CUSTOMER = Customer.CUSTOMER;

    /**
     * The table <code>public.customer_service</code>.
     */
    public static final CustomerService CUSTOMER_SERVICE = CustomerService.CUSTOMER_SERVICE;

    /**
     * The table <code>public.device</code>.
     */
    public static final Device DEVICE = Device.DEVICE;

    /**
     * The table <code>public.service</code>.
     */
    public static final Service SERVICE = Service.SERVICE;

    /**
     * The table <code>public.user</code>.
     */
    public static final User USER = User.USER;
}
