/*
 * This file is generated by jOOQ.
 */
package com.ninjarmm.dao.jooq.tables;


import com.ninjarmm.dao.jooq.Keys;
import com.ninjarmm.dao.jooq.Public;
import com.ninjarmm.dao.jooq.tables.records.CustomerServiceRecord;

import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row5;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CustomerService extends TableImpl<CustomerServiceRecord> {

    private static final long serialVersionUID = -1419657243;

    /**
     * The reference instance of <code>public.customer_service</code>
     */
    public static final CustomerService CUSTOMER_SERVICE = new CustomerService();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CustomerServiceRecord> getRecordType() {
        return CustomerServiceRecord.class;
    }

    /**
     * The column <code>public.customer_service.id</code>.
     */
    public final TableField<CustomerServiceRecord, UUID> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.customer_service.customerid</code>.
     */
    public final TableField<CustomerServiceRecord, UUID> CUSTOMERID = createField(DSL.name("customerid"), org.jooq.impl.SQLDataType.UUID, this, "");

    /**
     * The column <code>public.customer_service.serviceid</code>.
     */
    public final TableField<CustomerServiceRecord, UUID> SERVICEID = createField(DSL.name("serviceid"), org.jooq.impl.SQLDataType.UUID, this, "");

    /**
     * The column <code>public.customer_service.lastmodifiedby</code>.
     */
    public final TableField<CustomerServiceRecord, String> LASTMODIFIEDBY = createField(DSL.name("lastmodifiedby"), org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.customer_service.lastmodifieddatetime</code>.
     */
    public final TableField<CustomerServiceRecord, OffsetDateTime> LASTMODIFIEDDATETIME = createField(DSL.name("lastmodifieddatetime"), org.jooq.impl.SQLDataType.TIMESTAMPWITHTIMEZONE, this, "");

    /**
     * Create a <code>public.customer_service</code> table reference
     */
    public CustomerService() {
        this(DSL.name("customer_service"), null);
    }

    /**
     * Create an aliased <code>public.customer_service</code> table reference
     */
    public CustomerService(String alias) {
        this(DSL.name(alias), CUSTOMER_SERVICE);
    }

    /**
     * Create an aliased <code>public.customer_service</code> table reference
     */
    public CustomerService(Name alias) {
        this(alias, CUSTOMER_SERVICE);
    }

    private CustomerService(Name alias, Table<CustomerServiceRecord> aliased) {
        this(alias, aliased, null);
    }

    private CustomerService(Name alias, Table<CustomerServiceRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> CustomerService(Table<O> child, ForeignKey<O, CustomerServiceRecord> key) {
        super(child, key, CUSTOMER_SERVICE);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<CustomerServiceRecord> getPrimaryKey() {
        return Keys.CUSTOMER_SERVICE_PK;
    }

    @Override
    public List<UniqueKey<CustomerServiceRecord>> getKeys() {
        return Arrays.<UniqueKey<CustomerServiceRecord>>asList(Keys.CUSTOMER_SERVICE_PK);
    }

    @Override
    public List<ForeignKey<CustomerServiceRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<CustomerServiceRecord, ?>>asList(Keys.CUSTOMER_SERVICE__CUSTOMER_SERVICE_FK, Keys.CUSTOMER_SERVICE__CUSTOMER_SERVICE_FK_1);
    }

    public Customer customer() {
        return new Customer(this, Keys.CUSTOMER_SERVICE__CUSTOMER_SERVICE_FK);
    }

    public Service service() {
        return new Service(this, Keys.CUSTOMER_SERVICE__CUSTOMER_SERVICE_FK_1);
    }

    @Override
    public CustomerService as(String alias) {
        return new CustomerService(DSL.name(alias), this);
    }

    @Override
    public CustomerService as(Name alias) {
        return new CustomerService(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CustomerService rename(String name) {
        return new CustomerService(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CustomerService rename(Name name) {
        return new CustomerService(name, null);
    }

    // -------------------------------------------------------------------------
    // Row5 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row5<UUID, UUID, UUID, String, OffsetDateTime> fieldsRow() {
        return (Row5) super.fieldsRow();
    }
}
