/*
 * This file is generated by jOOQ.
 */
package com.ninjarmm.dao.jooq.tables;


import com.ninjarmm.dao.jooq.Keys;
import com.ninjarmm.dao.jooq.Public;
import com.ninjarmm.dao.jooq.tables.records.DeviceRecord;

import java.math.BigDecimal;
import java.time.OffsetDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import javax.annotation.processing.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row7;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "https://www.jooq.org",
        "jOOQ version:3.13.5"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Device extends TableImpl<DeviceRecord> {

    private static final long serialVersionUID = -1220015434;

    /**
     * The reference instance of <code>public.device</code>
     */
    public static final Device DEVICE = new Device();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DeviceRecord> getRecordType() {
        return DeviceRecord.class;
    }

    /**
     * The column <code>public.device.id</code>.
     */
    public final TableField<DeviceRecord, UUID> ID = createField(DSL.name("id"), org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.device.systemname</code>.
     */
    public final TableField<DeviceRecord, String> SYSTEMNAME = createField(DSL.name("systemname"), org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.device.devicetype</code>.
     */
    public final TableField<DeviceRecord, String> DEVICETYPE = createField(DSL.name("devicetype"), org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * The column <code>public.device.customerid</code>.
     */
    public final TableField<DeviceRecord, UUID> CUSTOMERID = createField(DSL.name("customerid"), org.jooq.impl.SQLDataType.UUID, this, "");

    /**
     * The column <code>public.device.lastmodifieddatetime</code>.
     */
    public final TableField<DeviceRecord, OffsetDateTime> LASTMODIFIEDDATETIME = createField(DSL.name("lastmodifieddatetime"), org.jooq.impl.SQLDataType.TIMESTAMPWITHTIMEZONE, this, "");

    /**
     * The column <code>public.device.devicecost</code>.
     */
    public final TableField<DeviceRecord, BigDecimal> DEVICECOST = createField(DSL.name("devicecost"), org.jooq.impl.SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>public.device.lastmodifiedby</code>.
     */
    public final TableField<DeviceRecord, String> LASTMODIFIEDBY = createField(DSL.name("lastmodifiedby"), org.jooq.impl.SQLDataType.VARCHAR, this, "");

    /**
     * Create a <code>public.device</code> table reference
     */
    public Device() {
        this(DSL.name("device"), null);
    }

    /**
     * Create an aliased <code>public.device</code> table reference
     */
    public Device(String alias) {
        this(DSL.name(alias), DEVICE);
    }

    /**
     * Create an aliased <code>public.device</code> table reference
     */
    public Device(Name alias) {
        this(alias, DEVICE);
    }

    private Device(Name alias, Table<DeviceRecord> aliased) {
        this(alias, aliased, null);
    }

    private Device(Name alias, Table<DeviceRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
    }

    public <O extends Record> Device(Table<O> child, ForeignKey<O, DeviceRecord> key) {
        super(child, key, DEVICE);
    }

    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    @Override
    public UniqueKey<DeviceRecord> getPrimaryKey() {
        return Keys.DEVICE_PK;
    }

    @Override
    public List<UniqueKey<DeviceRecord>> getKeys() {
        return Arrays.<UniqueKey<DeviceRecord>>asList(Keys.DEVICE_PK);
    }

    @Override
    public List<ForeignKey<DeviceRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<DeviceRecord, ?>>asList(Keys.DEVICE__DEVICES_FK);
    }

    public Customer customer() {
        return new Customer(this, Keys.DEVICE__DEVICES_FK);
    }

    @Override
    public Device as(String alias) {
        return new Device(DSL.name(alias), this);
    }

    @Override
    public Device as(Name alias) {
        return new Device(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Device rename(String name) {
        return new Device(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Device rename(Name name) {
        return new Device(name, null);
    }

    // -------------------------------------------------------------------------
    // Row7 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row7<UUID, String, String, UUID, OffsetDateTime, BigDecimal, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }
}
